In [1]:
import numpy as np 

a = np.random.randn(5)
print (a)

[ 0.57932256 -0.01150662  0.99921739  1.37606038  0.38896248]


In [2]:
print (a.shape)

(5,)


In [3]:
print (a.T)

[ 0.57932256 -0.01150662  0.99921739  1.37606038  0.38896248]


In [4]:
print (np.dot(a,a.T))

3.37901642684


In [5]:
a = np.random.randn(5,1)
print (a)

[[-0.23401148]
 [ 0.22045584]
 [ 1.84830808]
 [ 1.03366772]
 [ 0.11582183]]


In [7]:
print (a.T)

[[-0.23401148  0.22045584  1.84830808  1.03366772  0.11582183]]


In [6]:
print (np.dot(a,a.T))

[[ 0.05476137 -0.0515892  -0.43252531 -0.24189012 -0.02710364]
 [-0.0515892   0.04860078  0.40747031  0.22787808  0.0255336 ]
 [-0.43252531  0.40747031  3.41624276  1.91053639  0.21407443]
 [-0.24189012  0.22787808  1.91053639  1.06846895  0.11972129]
 [-0.02710364  0.0255336   0.21407443  0.11972129  0.0134147 ]]
